RecycloPortal/Controllers/CupomController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RecicloPortal.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RecicloPortal.Controllers
{
    public class CupomController : Controller
    {
        private readonly ILogger<CupomController> _logger;

        public CupomController(ILogger<CupomController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecycloPortal/Controllers/ResgateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RecicloPortal.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RecicloPortal.Controllers
{
    public class ResgateController : Controller
    {
        private readonly ILogger<ResgateController> _logger;

        public ResgateController(ILogger<ResgateController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecycloPortal/Views/Cupom/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Cupons Disponíveis</title>
    <link href="style.css" rel="stylesheet" type="text/css" />
</head>
<center>
    <h1>Re-Ciclo</h1>
</center>
<section>
    <div>
        <ul>
            <li>
                <a href="home">Inicial</a>
            </li>
            <li>
                <a href="cadastrar">Cadastro</a>
            </li>
            <li>
                <a href="agendamento">Agendamento</a>
            </li>
            <li>
                <a href="pontuacao">Pontuação</a>
            </li>
            <li>
                <a href="material">Materiais</a>
            </li>
        </ul>
    </div>
</section>

<center>
    <h2>Cupons Disponíveis</h2>
</center>
<form name="input"
      action="pontuacao.html"
      method="get">
    <!-- <center>
      <label>Cupons Disponíveis</label>
    </center> -->
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <label>Troque 10.000 pontos por 10% de desconto
    </div>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <img src="imagens/cupom_1.jpg" height="100" width="150" align="midlle">
        </label>
    </div>
    <br>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <label>Troque 9.000 pontos por 9% de desconto
    </div>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <img src="imagens/cupom_2.jpg" height="100" width="150" align="midlle">
        </label>
    </div>
    <br>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <label>Troque 7.000 pontos por 7% de desconto
    </div>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <img src="imagens/cupom_3.jpg" height="100" width="150" align="midlle">
        </label>
    </div>
    <br>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <label>Troque 8.000 pontos por 8% de desconto
    </div>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <img src="imagens/cupom_4.jpg" height="100" width="150" align="midlle">
        </label>
    </div>
    <br>
    <center>
        <input type="button" id="botao" value="Confirmar " onclick="location.href='@Url.Action("Index", "Resgate")'" />
    </center>
</form>
</html>