RecycloPortal/Controllers/CupomController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RecicloPortal.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RecicloPortal.Controllers
{
    public class CupomController : Controller
    {
        private readonly ILogger<CupomController> _logger;

        public CupomController(ILogger<CupomController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecycloPortal/Controllers/PontuacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RecicloPortal.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RecicloPortal.Controllers
{
    public class PontuacaoController : Controller
    {
        private readonly ILogger<PontuacaoController> _logger;

        public PontuacaoController(ILogger<PontuacaoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecycloPortal/Views/Pontuacao/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Pontuação</title>
    <link href="style.css" rel="stylesheet" type="text/css" />
</head>
<center>
    <h1>Re-Ciclo</h1>
</center>
<section>
        <div>
            <ul>
                <li>
                    <a href="hone">Inicial</a>
                </li>
                <li>
                    <a href="agendamento">Agendamento</a>
                </li>
                <li>
                    <a href="cupom">Cupom</a>
                </li>
                <li>
                    <a href="pontuacao">Pontuação</a>
                </li>
                <li>
                    <a href="resgate">Resgate de Pontos</a>
                </li>
                <li>
                    <a href="material">Materiais</a>
                </li>
            </ul>
        </div>
</section>

<center>
    <h2>Pontuação</h2>
</center>
<form action="pontuacao.html" method="post">
    <!--<center>
      <label>Pontuação</label>
    </center> -->
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <label>Saldo de pontos
    </div>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        </label>
    </div>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <img src="imagens/pontuação.jpg" height="100" width="150" align="midlle">
        </label>
    </div>
    <br>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        </label>
    </div>
    <div class="container" style="
  align-items: center;
  display: flex;
  justify-content: center;
">
        <label> Clique para ver seus pontos
    </div>
    <br>
    <center>
        <input type="button" id="botao" value="Resgatar cupom" onclick="location.href='@Url.Action("Index", "Cupom")'" />
    </center>
</form>
</html>